### PR TITLE
Hot fix for missing translation

### PR DESCRIPTION
**Pull request by eric3873**

### CODE REVIEW

**Review by jimklimov — APPROVED** [review]

**Review by aquette — APPROVED** [review]
LGTM for a hotfix, to be discussed with @etnKlendathu and @jimklimov for the full covering solution WRT _tr with params and strings extraction

**Review by aquette — CHANGES_REQUESTED** [review]
not working as is, need a better / proper fix

**Comment by eric3873** [comment]
The hot fix don't work correctly. To be investigate more.

**Comment by aquette** [comment]
good fix done: https://github.com/42ity/fty-common-translation/pull/44
hence declining the present PR

**Review by aquette — APPROVED** [review]

**Pull request merged**
